services:
  comfyui:
    build: comfy
    ports:
      - "8188:8188"
    volumes:
      - comfy-nfs:/home/ubuntu/comfy
      - comfy-venv:/home/ubuntu/venv
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  comfy-venv:
  comfy-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER:-nas-fast.home.dynamis.bbrfkr.net},vers=4,rw
      device: ":${NFS_SHARE_POINT:-/comfy}"